# Generated by Django 5.0.3 on 2024-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_message_function_call_alter_message_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
    ]
