# Generated by Django 5.0.3 on 2024-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_note_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="systemprompt",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="user",
            new_name="owner",
        ),
    ]
